project:
  type: website # Indicates website format

website:
  title: "D. Sebastian Heredia" # Sets side-wide title
  navbar: # Indicates navigation bar
    left: 
      - href: engineering.qmd
        text: Engineering Class Projects
      - href: projects.qmd
        text: Personal Projects
      - href: music.qmd
        text: Music & Performance
      - href: outdoors.qmd
        text: Sports & Outdoors
      - text: E155 Microprocessor Labs
        menu:
          - href: E155_Lab_1.qmd
            text: Lab 1 - FPGA & MCU Setup
          - href: E155_Lab_2.qmd
            text: Lab 2 - Time Multiplexing
          - href: E155_Lab_3.qmd
            text: Lab 3 - Keypad Scanner
          - href: E155_Lab_4.qmd
            text: Lab 4 - Digital Audio
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: flatly # Applies built-in "jolla" style across site
    css: styles.css # Adds custom style/theme sheets acrros site
    toc: false # toc = Table of Contents
    include-in-header:
      - text: '<meta name="viewport" content="width=device-width, initial-scale=0.5, maximum-scale=0.5, user-scalable=no">'

# Darkly, Cyborg, United, Solar
# Original: flatly